### PR TITLE
[ENH] LLM Extractions added

### LINKED ISSUE #14: LLM extractions
- Extracts the value for specified parameters from the user query using the LLM
- Puts 'None' in case a parameter is not specified

### PR DESCRIPTION
**Pull request by Raya679**
- Closes #14 

Changes proposed in this pull request:

- Extracts the values of specified parameters from the user query in JSON format.
- In case a parameter is not specified it puts 'None'.

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [x] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [x] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

**Review by rmanaem — CHANGES_REQUESTED** [review]
Thanks for the PR @Raya679!
I tried a query and it works great! 
let's add some tests before we merge 🍒

**Comment by Raya679** [comment]
Hi @rmanaem,
I have added some tests and made some minor changes to the file structure.
Please let me know if any changes are required!

Thanks!!

**Review by rmanaem — CHANGES_REQUESTED** [review]
Thanks for making the changes @Raya679!
🍒 I have a couple of points:
- Regarding the tests, I think this is a good case for parameterized tests. This would eliminate the need for two similar fixtures and tests. See API repo tests for examples on parameterized tests.
- There seems to be a lot of duplication between the code in `extractions` and `LLM_Extractions` folders is that intentional? or left over from refactor?
- Please move the README.md to the root level so it is visible at first glance

**Comment by Raya679** [comment]
Hi @rmanaem ,
Thanks for the review! I have made the required changes.
Regarding the duplication I had just renamed the folder extractions to LLM_extractions to avoid confusion with the python file.

The current file stucture is something like this
```
.
├── app
│   ├── __init__.py
│   └── LLM_extractions
│       ├── extractions.py
│       └── __init__.py
├── LICENSE
├── README.md
├── requirements.txt
└── tests
    ├── __init__.py
    └── test_extractions.py
```

**Review by rmanaem — CHANGES_REQUESTED** [review]
This all looks great @Raya679!
:cherries: One last thing I'd suggest adding more test cases perhaps to make sure the model can extract assessment, diagnosis, and modality with no problem and it can distinguish between subjects with a diagnosis and healthy controls.

**Comment by Raya679** [comment]
Hii @rmanaem ,
Thanks for pointing that out!! I have added more testcases
Please review them and let me know if any further changes are needed.

**Review by rmanaem — APPROVED** [review]
Thanks and great work @Raya679! :cook:

**Pull request merged**
